
name: $(VersionNumberMajor).$(VersionNumberMinor)$(Rev:.rrrr)

resources:
- repo: self
  fetchDepth: 15

variables: # pipeline-level
- name: 'VersionNumberMajor'
  value:  '0'
- name: 'VersionNumberMinor'
  value: '1'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    variables: # job-level
      "Build.Configuration": 'Release'
      "DotNetCore.Version": '2.2.207'
    pool:
      name: DCT
      demands:
      - IsBuildServer
      - ServiceFabricSDK
      #- ServiceFabricSDKVersion -equals 65

    steps:
	- task: DotNetCoreInstaller@0
	  displayName: 'Use .NET Core sdk $(DotNetCoreVersion)'
	  inputs:
		version: $(DotNetCoreVersion)

