CREATE TABLE [ReferenceInput].[AppsEarningHistory_ApprenticeshipEarningsHistory]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AppIdentifier] [nvarchar](2000) NULL,
	[AppProgCompletedInTheYearInput] [bit] NULL,
	[CollectionYear] [nvarchar](2000) NULL,
	[CollectionReturnCode] [nvarchar](2000) NULL,
	[DaysInYear] [int] NULL,
	[FworkCode] [int] NULL,
	[HistoricEffectiveTNPStartDateInput] [datetime] NULL,
	[HistoricEmpIdEndWithinYear] [bigint] NULL,
	[HistoricEmpIdStartWithinYear] [bigint] NULL,
	[HistoricLearner1618StartInput] [bit] NULL,
	[HistoricPMRAmount] [decimal](12, 5) NULL,
	[HistoricTNP1Input] [decimal](12, 5) NULL,
	[HistoricTNP2Input] [decimal](12, 5) NULL,
	[HistoricTNP3Input] [decimal](12, 5) NULL,
	[HistoricTNP4Input] [decimal](12, 5) NULL,
	[HistoricTotal1618UpliftPaymentsInTheYearInput] [decimal](12, 5) NULL,
	[HistoricVirtualTNP3EndOfTheYearInput] [decimal](12, 5) NULL,
	[HistoricVirtualTNP4EndOfTheYearInput] [decimal](12, 5) NULL,
	[HistoricLearnDelProgEarliestACT2DateInput] [datetime] NULL,
	[LatestInYear] [bit] NOT NULL,
	[LearnRefNumber] [nvarchar](2000) NULL,
	[ProgrammeStartDateIgnorePathway] [datetime] NULL,
	[ProgrammeStartDateMatchPathway] [datetime] NULL,
	[ProgType] [int] NULL,
	[PwayCode] [int] NULL,
	[STDCode] [int] NULL,
	[TotalProgAimPaymentsInTheYear] [decimal](12, 5) NULL,
	[UptoEndDate] [datetime] NULL,
	[UKPRN] [int] NOT NULL,
	[ULN] [bigint] NOT NULL,
	CONSTRAINT [PK_ReferenceInput.AppsEarningHistory_ApprenticeshipEarningsHistory] PRIMARY KEY ([Id]),
)
