CREATE TABLE [ReferenceInput].[FRM_FrmLearner]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UKPRN] [bigint] NOT NULL,
	[ULN] [bigint] NOT NULL,
	[AimSeqNumber] [int] NOT NULL,
	[LearnRefNumber] [nvarchar](2000) NULL,
	[LearnAimRef] [nvarchar](2000) NULL,
	[LearningAimTitle] [nvarchar](2000) NULL,
	[OrgName] [nvarchar](2000) NULL,
	[PartnerOrgName] [nvarchar](2000) NULL,
	[ProgTypeNullable] [int] NULL,
	[StdCodeNullable] [int] NULL,
	[FworkCodeNullable] [int] NULL,
	[PwayCodeNullable] [int] NULL,
	[LearnStartDate] [datetime] NOT NULL,
	[AimType] [int] NOT NULL,
	[FundModel] [int] NOT NULL,
	[PrevUKPRN] [bigint] NULL,
	[PMUKPRN] [bigint] NULL,
	[PartnerUKPRN] [bigint] NULL,
	[PrevLearnRefNumber] [nvarchar](2000) NULL,
	[SWSupAimId] [nvarchar](2000) NULL,
	[LearnPlanEndDate] [datetime] NOT NULL,
	[LearnActEndDate] [datetime] NULL,
	[PriorLearnFundAdj] [int] NULL,
	[OtherFundAdj] [int] NULL,
	[CompStatus] [int] NOT NULL,
	[Outcome] [int] NULL,
	CONSTRAINT [PK_ReferenceInput.FRM_FrmLearner] PRIMARY KEY ([Id]),
)
