CREATE TABLE [ReferenceInput].[LARS_LARSLearningDelivery]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[LearnAimRef] [nvarchar](2000) NULL,
	[LearnAimRefType] [nvarchar](2000) NULL,
	[LearnAimRefTitle] [nvarchar](2000) NULL,
	[LearnAimRefTypeDesc] [nvarchar](2000) NULL,
	[EnglPrscID] [int] NULL,
	[NotionalNVQLevel] [nvarchar](2000) NULL,
	[NotionalNVQLevelv2] [nvarchar](2000) NULL,
	[FrameworkCommonComponent] [int] NULL,
	[LearnDirectClassSystemCode1] [nvarchar](2000) NULL,
	[LearnDirectClassSystemCode2] [nvarchar](2000) NULL,
	[LearnDirectClassSystemCode3] [nvarchar](2000) NULL,
	[SectorSubjectAreaTier1] [decimal](5, 2) NULL,
	[SectorSubjectAreaTier2] [decimal](5, 2) NULL,
	[LearningDeliveryGenre] [nvarchar](2000) NULL,
	[RegulatedCreditValue] [int] NULL,
	[EnglandFEHEStatus] [nvarchar](2000) NULL,
	[AwardOrgCode] [nvarchar](2000) NULL,
	[EFACOFType] [int] NULL,
	[GuidedLearningHours] [int] NULL,
	[EffectiveFrom] [datetime] NOT NULL,
	[EffectiveTo] [datetime] NULL,
	CONSTRAINT [PK_ReferenceInput.LARS_LARSLearningDelivery] PRIMARY KEY ([Id]),
)
